name: Auto-upload Distro announcements to Bazaar

on:
  discussion:
    types: [pinned]    

jobs:
 sendAnnouncement:
  runs-on: ubuntu-latest
  steps:
  
  - name: Fetch announcement
    id: announcement
    run: |
      category="${{ github.event.discussion.category.name }}"
      title="${{ github.event.discussion.title }}"
      echo "::set-output name=title::${title}"
      if [[ "${category}" == "Releases" && "${title}" == *"Distro"* ]]
      then
        echo "::set-output name=is_distro::true"
      else
        echo "::set-output name=is_distro::false"
      fi

  - name: Fetch summary
    id: summary
    run: |
      echo "${{ github.event.discussion.body }}" > body.txt
      sed -nr 's/.*### Brief description of the announcement(.*)### Detailed context.*/\1/p' <body.txt >summary.txt
      echo "::set-output name=body::$(cat summary.txt)"

  - name: Fetch description
    id: description
    run: |
      echo "::set-output name=body::"  

  - name: Fetch current date
    id: date
    run: |
        echo "::set-output name=date::$(date +'%Y%m')"
        echo "::set-output name=date_spelled::$(date +'%B %Y')"

  - name: Repository Dispatch
    uses: peter-evans/repository-dispatch@v1.1.3
    with:
      token: ${{ secrets.CODE_REPO_ACCESS_TOKEN }}
      repository: icub-tech-iit/code
      event-type: announcement_launched
      client-payload: '{"description": ${{ steps.description.outputs.body }}, "id": "${{ steps.date.outputs.date }}", "title": ${{ steps.announcement.outputs.title }}, "date": "${{ steps.date.outputs.date_spelled }}", "summary": "${{ steps.summary.outputs.body }}", "image": "???", "type" : "announcement_launched", "release": "${{ steps.announcement.outputs.is_distro }}"}'
